buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Versi ini paling aman untuk sistem GitHub sekarang
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.application'

android {
    compileSdk 33
    namespace 'com.ipank.loader'

    defaultConfig {
        applicationId "com.ipank.loader"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    // Penunjuk jalan file agar robot tidak nyasar
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['.']
            res.srcDirs = [] // Kita kosongkan dulu agar tidak error resource
        }
    }
}
