name: Build APK Ipank
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Rakit APK Sultan
        run: |
          # Buat folder standar
          mkdir -p app/src/main/java/com/ipank/loader
          mkdir -p app/src/main/res/layout
          # Pindahkan file yang sudah ada di GitHub ke folder rakitan
          cp MainActivity.java app/src/main/java/com/ipank/loader/
          cp AndroidManifest.xml app/src/main/
          # Bikin tampilan kosong saja
          echo '<?xml version="1.0" encoding="utf-8"?><LinearLayout xmlns:android="http://android.com" android:layout_width="match_parent" android:layout_height="match_parent" />' > app/src/main/res/layout/activity_main.xml
          # GAS RAKIT!
          gradle assembleDebug
      - name: Ambil Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: Ipank-Loader-Sultan
          path: "**/*.apk"
